name: Remove Labels on Dislike

on:
  issue_comment:
    types: [created]

jobs:
  process-dislike:
    if: github.event.comment.reactions['-1'] > 0
    runs-on: ubuntu-latest

    steps:
      - name: Remove priority labels if bot comment is downvoted
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = context.payload.comment;
            const issue = context.payload.issue;
            const sender = context.payload.sender.login;
            const botUser = context.actor;

            if (sender === botUser) return;

            const isOurBotComment = comment.body.startsWith("The following label(s) were added to this issue");
            if (!isOurBotComment) return;

            const labelsToRemove = ["Low Priority", "Medium Priority", "HIGH PRIORITY", "deployment", "enhancement", "bug"];
            const existingLabels = issue.labels.map(l => l.name);
            const matchedLabels = labelsToRemove.filter(l => existingLabels.includes(l));

            for (const label of matchedLabels) {
              await github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issue.number,
                name: label
              });
            }
