name: Weekly Report

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at 00:00 UTC
  push:
    paths:
      - 'reportoverride'  # Manual override trigger

jobs:
  generate-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install PyGithub

      - name: Generate and post report
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
        run: |
          python .github/scripts/post_report.py
